### ISSUE TITLE
Please correct github link in "Meteor atmosphere".

### ISSUE THREAD

**Issue by thearabbit** [NilsDannemann/meteor-pdfmake#1]
Please correct github link in "Meteor atmosphere".
I wait for ready...

**Comment by NilsDannemann** [comment]
I'll try my best. 
It's my first package so it will probably take me a while to figure everything out.

**Comment by NilsDannemann** [comment]
The link works now, but I seem to have made an error somewhere else.
Currently I can't add the package. I get an error. I'll fix that today/tomorrow.

**Comment by NilsDannemann** [comment]
Okay, everything should work now.
I'll start with the docs later.

**Comment by thearabbit** [comment]
look great.
