### ISSUE TITLE
How to parse template data? 

### ISSUE THREAD

**Issue by Ajaxsoap** [NilsDannemann/meteor-pdfmake#3]
Hi,
Thanks for this package!

The example is working perfectly, text, styling and image :+1:  

But all the generated content on pdf is explicitly defined inside the event handlers, basically its all static, what if i want to fetch my data inside my template like {{name}},{{address}} etc. Is this possible on this package?

**Comment by NilsDannemann** [comment]
Hi Ajaxsoap,

I hope I understand you correctly. 
Yes, this should be possible.

In the "more complex Example" from the quick docs I wrote you have your variables.
`var myHeadline = this.myHeadline;`
`var myFirstItem = this.myFirstItem;`
`var mySecondItem = this.mySecondItem;`
`var myParagraph = this.myParagraph;`

You can use those however you want to get your data.

## Some exmaples:

**To output the current users name** you could change this:
`var myHeadline = this.myHeadline;`
like so:
`var myHeadline = Meteor.user().profile.name;`

**To output values from any collection** you could change this:
`var myFirstItem = this.myFirstItem;`
like so:
`var myFirstItem = Customers.findOne(your criteria here).adress;`

Does this answer your question?
If not: Feel free to ask more. :-)

**Comment by Ajaxsoap** [comment]
Yeah sort of, let say, i have this on my template:

```
<template name="hello">
    <div id="body">
      <p>
        <strong>Header Title</strong>
      </p>
      <p>
        Subheader Title
      </p>
      <p>
        Another subheader title
      </p>
      <table>
        {{#each}}
        <tr>
          <td>{{value 1}}</td>
          <td>{{value 2}}</td>
        </tr>
        {{/each}}       
      </table>
    </div>
</template>
```

How should I declare it on my submit event handler?

**Comment by NilsDannemann** [comment]
Oh I see. Actually I've never thought about that. But I can see that this would be handy.

It's getting a bit late over here so I'll have to look for a solution tomorrow.
Of the top of my head I'd try something with the forEach() method.

Maybe somehow like this(see answer from **Sekai**):
http://stackoverflow.com/questions/12956438/accessing-mongodb-collection-values-in-javascript

Let me know if this works for you.
Otherwise I'll take a look at it tomorrow.

**Comment by Ajaxsoap** [comment]
Thanks @NilsDannemann! Appreciate your help!

I will check on this.

**Comment by NilsDannemann** [comment]
Hey man,

you can iterate over a collection like so:
`var customerNames = Customers.find().map(function(i){`
`return i.name;`
`});`

Then you can implement it in your pdf definition like so:
`{ text: Some Text, style: 'headline' },`
`customerNames ,`
`{ text: Some Text, style: 'headline' },`

This will output all customer names in your collection.
However: You'll have to play around with the formatting and see what you get. Hope this works for you :-)

**Comment by Ajaxsoap** [comment]
Hi Nils,

It worked but the value that the pdf generated is the actual _id of the field: 

```
var claimant = Claim.findOne().enrollmentId;
```

How do I transform the _id into it's actual value? 

Also, the Date(), I tried to format it to Date.format('mm do yy'), no effect. Even moment.format() has no effect. it display the ISO format "Sun Aug 16 2015 16:32:01 GMT+0800 (PHT)"

**Comment by Ajaxsoap** [comment]
There's no example on  the main pdfmake [docs](http://pdfmake.org/index.html#/gettingstarted) on how the date will be treated and the options that we can inject. I guess, we'll have to improvise this, i don't expect you to solve this issue as you are not the author of this library.

Thanks @NilsDannemann! I will do update this thread if I found a workaround.

**Comment by Ajaxsoap** [comment]
This 

```
var claimant = Claim.findOne().enrollmentId;
```

enrollmentId Is actually a relationship from other collection, that's why the _id is parsing on the pdf, I tried other field and it worked! :)

I guess Date is the next issue.

**Comment by NilsDannemann** [comment]
Hey man,

happy that you found a solution. :+1: 

**To the date formatting:**
I'm not sure how you implemented the date method, but I usually just do dates it like this:
`var date = new Date();`

`date.toDateString(); //gives you: "Wed Jun 04 2014"`
`date.toLocaleDateString(); gives you: //"6/4/2014"`
`date.toLocaleTimeString(); gives you: //"1:30:39 PM"`

Hope it helps.

**Comment by Ajaxsoap** [comment]
I used the toString(), oh I've overlooked it, it should be toDateString() since i am dealing with Date(). haha

Thanks a lot @NilsDannemann ! :+1:

**Comment by NilsDannemann** [comment]
No worries, happy to help. :-)

Hehe, yeah, I've also written these date methods in my notwbook since I keep forgetting them.

**Comment by Ajaxsoap** [comment]
I know that this is too much but is the user input form possible on this library?

**Comment by NilsDannemann** [comment]
What do you mean? Can you post an example?

Just an input form, that adds it's content to the pdf?

**Comment by Ajaxsoap** [comment]
Yeah, the data submitted from the form will be the pdf content. 

Ex. 
Form input
Name: ________
Phone: ________
Address: ______

```
var name = this.name;
var phone = this.phone;
var address = this.address;

var docDefinition = {
  pageSize: 'A4',
            pageMargins: [ 30, 25, 30, 25 ],
            // Content with styles
            content: [
              {
                text: ['Name: ',name],
                style: 'style'
              },
             {
                text: ['Address: ',address],
                style: 'style'
              },
              {
                text: ['Phone: ',phone],
                style: 'style'
              },
},

```

I know this a long shot question but is this possible?

Thanks!

**Comment by NilsDannemann** [comment]
Sure, that should be possible.

You could, for example, use the submit event of that form like so:

**The form:**
`<template name="myTemplate">`
&nbsp;&nbsp;&nbsp;&nbsp;`<form class="my_form">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  `<input class="my_input" type="text" name="name">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    `<input type="submit" value="submit">`
&nbsp;&nbsp;&nbsp;&nbsp;   `</form>`
`</template>`

**The event:**
`Template.myTemplate.events({`
&nbsp;&nbsp;&nbsp;&nbsp;`'submit .my_form': function(event) {`
&nbsp;&nbsp;&nbsp;&nbsp;`var name = event.target.name.value;`

&nbsp;&nbsp;&nbsp;&nbsp;`//define pdf`
&nbsp;&nbsp;&nbsp;&nbsp;`var docDefinition = {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`pageSize: 'A4',`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`pageMargins: [ 30, 25, 30, 25 ],`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `content: [`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`{`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `text: ['Name: ',name],`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `style: 'style'`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `}`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; `]`
&nbsp;&nbsp;&nbsp;&nbsp;  `};`
&nbsp;&nbsp;&nbsp;&nbsp;`//generate pdf`
&nbsp;&nbsp;&nbsp;&nbsp;`pdfMake.createPdf(docDefinition).open();`

&nbsp;&nbsp;&nbsp;&nbsp;`// clear form & prevent browser refresh`
&nbsp;&nbsp;&nbsp;&nbsp;`event.target.name.value = "";`
&nbsp;&nbsp;&nbsp;&nbsp;`event.preventDefault();`
&nbsp;&nbsp;&nbsp;&nbsp;`}`
`});`

Note: I'm currently not on my computer so I couldn't test this. But I think it should work.

**Comment by Ajaxsoap** [comment]
Hell yeah! I think this setup is ok if for generating pdf on the client and not saving on db. 

You ROCK @NilsDannemann!

**Comment by Ajaxsoap** [comment]
Yeah @NilsDannemann! 

I've tried it and It worked! :+1:

**Comment by NilsDannemann** [comment]
Awesome man, happy to hear that!
