### ISSUE TITLE
Render pdf table

### ISSUE THREAD

**Issue by Ajaxsoap** [NilsDannemann/meteor-pdfmake#4]
Hello @NilsDannemann ,

I am wondering if how do I display each row for each data on the table of names? Let say, iterate the names for x collections.

I tried the mapping but it displays all in one row for all data, is there a command that I can use to display each data per row?

**Comment by NilsDannemann** [comment]
Hey @Ajaxsoap,

I stubled across the same issue a few days ago and so far could not find a solution. :-/
That a shame, because this is actually quite a useful feature.

I'll give it another try in a few days. 
Hopefully I can find a way to make this happen.

**Comment by Ajaxsoap** [comment]
Thanks @NilsDannemann !

Yeah, I agree, of all the pdf generators out there, pdfmake is the most easy to style in my opinion. But, the features for iterate a documents in a collection within the table is hard to implement. 

I will try to research again, probably, on pdfmake main repo issue tracker.
