### ISSUE TITLE
Update package with last release of pdfMake

### ISSUE THREAD

**Issue by jgauthie** [NilsDannemann/meteor-pdfmake#6]
Hi,

I'm currently using your package with meteor, and the release of pdfMake you are using seems to be a bit old (and with bug: this release seems to have a header/footer bug:
https://github.com/bpampuch/pdfmake/issues/227 which is fixed in pdfMake > 0.1.17). 
I don't know if you are still working on this package

Thanks for this package anyway,
Regards,
Julien

**Comment by NilsDannemann** [comment]
Hi Julien,

I'm currently extremely short on time. 

I quickly updated the package to pdfmake version 0.1.20, but had not time for testing. 
Does this work for you?

**Comment by jgauthie** [comment]
Hi Nils,

Thanks a lot for your time, it's working like it should now !

I'm using pdfmake to make basic PDF so i don't have any test on it for now...

pdfMake 0.1.20 seems to be a pretty stable release so we'll see.
Thanks again for your time and for this package !

Julien
