### ISSUE TITLE
Server side pdf generation error

### ISSUE THREAD

**Issue by daupawar** [NilsDannemann/meteor-pdfmake#8]
I am getting following error 
`Exception while invoking method 'GeneratePdf' ReferenceError: pdfMake is not defined
server/lib/MakePdf.Methods.js`

This is  my server side code

`Meteor.methods({
    'GeneratePdf': function (DocDef) {
        pdfMake.createPdf(DocDef).getDataUrl(function (dataURL) {
            return dataURL;
        });
    },
});`

**Comment by NilsDannemann** [comment]
Hey daupawar,

unfortunately this package just adds the client-side version. I noted this at the top of the docs.

I'd love to implement the server-side functionality as well, but couldn't make it work so far.
